[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unimorph-backend-eee"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.entry-points."eee.backends.v1"]
el = "unimorph_backend_eee:UniMorphBackend"
grc = "unimorph_backend_eee:UniMorphBackend"

[tool.hatch.build.targets.wheel]
packages = ["src/unimorph_backend_eee"]

[tool.pytest.ini_options]
testpaths = ["tests"]
